# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Python base image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the contents of the repository to the working directory
COPY . .

# Install the project dependencies
RUN pip install --no-cache-dir httpx==0.24.1 click==8.1.7 mcp==0.1.0

# Set environment variables for Airflow connection
ENV AIRFLOW_HOST=${AIRFLOW_HOST}
ENV AIRFLOW_USERNAME=${AIRFLOW_USERNAME}
ENV AIRFLOW_PASSWORD=${AIRFLOW_PASSWORD}

# Expose the port that the server will run on
EXPOSE 8000

# Command to run the server
CMD ["python", "src/server.py"]
